logging:
  level:
    root: info
    com.project.repring: debug

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    operations-sorter: alpha, method
    tags-sorter: alpha
    groups-order: DESC
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

# JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL570Dialect